
default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
development:
  <<: *default
  database: Twitter4Zombies_development
test:
  <<: *default
  database: Twitter4Zombies_test
production:
  <<: *default
  database: Twitter4Zombies_production
  username: Twitter4Zombies
  password: <%= ENV['Twitter4Zombies_DATABASE_PASSWORD'] %>
